fix(readme): update component example stylesheet
webex/sdk-component-adapter pull request #207
Opened 2021-09-29 23:57 UTC by jonniespratley

2021-09-30 01:44 UTC, lalli-flores requested changes
This is a doc change, and shouldn't trigger a version bump. Please update your commit type
```
docs(readme): update component example stylesheet

2021-09-30 01:56 UTC, jonniespratley commented
> docs(readme): update component example stylesheet

Ok, will amend the commit, :)

2021-09-30 02:03 UTC, lalli-flores approved these changes

2021-09-30 02:05 UTC, merged

2021-10-04 16:40 UTC, webex-components-publisher commented
:tada: This PR is included in version 1.64.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@webex/sdk-component-adapter/v/1.64.0)
- [GitHub release](https://github.com/webex/sdk-component-adapter/releases/tag/v1.64.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: